# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnvNo8vhF_aEAM9Psl7bbKIMsnO89nV-
"""

import cv2 as cv
import time

face_cascade = cv.CascadeClassifier("/content/haarcascade_frontalface_default.xml")


url = ""
cap = cv.VideoCapture(0)
cap.open(url)


while True:
  ret , frame = cap.read()
  gray  = cv.cvtColor(frame,cv.COLOR_BGR2GRAY)
  face = face_cascade.detectMultiScale(gray,1.1,4)
  for (x,y,w,h) in face:
    cv.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
  plt.imshow("Frame",frame)

  if cv.waitKey(20) & 0xff == ord('q'):
    break

cap.release()
cv.destroyAllWindows()